on:
  push:
    branches:
      - main
    paths:
      - '**.qmd'
      - '**.R'
  schedule:
      - cron: "03 14,21 * * MON-FRI"
  workflow_dispatch:

name: build-dash

permissions:
  contents: write

jobs:
  build-dash:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:

    - uses: actions/checkout@v3

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: pre-release

    - uses: r-lib/actions/setup-r@v2

    - name: Add Ubuntu dependencies
      run: sudo apt-get install libglpk40

    - uses: r-lib/actions/setup-renv@v2

    - name: Cache targets data
      uses: actions/cache@v3
      with:
          path: _targets
          key: ${{ runner.os }}-targets-v1-${{ hashFiles('**/cache.log') }}
          restore-keys: |
              ${{ runner.os }}-targets-v1-

    - name: Build Pipeline and Dashboard
      run: Rscript -e 'targets::tar_make()'

    - name: Was the dashboard updated?
      id: dashboard-updated
      run: |
        if [[ $(git status --porcelain -- index.html index_files/) ]]; then
          echo "has_update=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Push Built Dashboard
      if: steps.dashboard-updated.outputs.has_update == 'true'
      run: |
          git config --global user.name 'gha update bot'
          git config --global user.email 'gadenbuie@users.noreply.github.com'
          git add --all
          git commit --allow-empty -m "[auto] Build Dashboard $(TZ=America/New_York date +'%Y-%m-%d %H:%M')"
          git push

    - name: Publish to Quarto Pub
      if: steps.dashboard-updated.outputs.has_update == 'true'
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: quarto-pub
        render: false
        path: index.qmd
        QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}
